import AppKit

/// Polls the general pasteboard and records every new copy into the store.
final class ClipboardMonitor {
    private let pb = NSPasteboard.general
    private let store: HistoryStore
    private var lastChange: Int
    private var timer: Timer?

    /// Markers password managers and other apps put on data that must not be recorded.
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
    ]

    private static let richLimit = 400_000
    private static let imageLimit = 40_000_000

    init(store: HistoryStore) {
        self.store = store
        lastChange = pb.changeCount
    }

    func start() {
        let t = Timer(timeInterval: 0.35, repeats: true) { [weak self] _ in self?.poll() }
        t.tolerance = 0.1
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    /// Call right after WolfClip itself wrote to the pasteboard so the write is not recorded again.
    func skipCurrent() {
        lastChange = pb.changeCount
    }

    private func poll() {
        let change = pb.changeCount
        guard change != lastChange else { return }
        lastChange = change
        guard !Prefs.shared.paused else { return }
        capture()
    }

    private func capture() {
        let types = Set((pb.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.ignoredTypes) else { return }
        let app = NSWorkspace.shared.frontmostApplication
        let bundleID = app?.bundleIdentifier
        let appName = app?.localizedName

        func record(_ fingerprint: String, _ make: () -> ClipItem?) {
            if store.promote(fingerprint: fingerprint, bundleID: bundleID, appName: appName) { return }
            guard var item = make() else { return }
            item.appBundleID = bundleID
            item.appName = appName
            store.add(item)
        }

        // Files copied in Finder (they also carry a name string and an icon, so check them first).
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path)
            let fp = "files:" + Clip.sha(Data(paths.joined(separator: "\n").utf8))
            record(fp) { ClipItem(kind: .files, text: paths.joined(separator: "\n"), files: paths, fingerprint: fp) }
            return
        }

        if let s = pb.string(forType: .string), !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let fp = "text:" + Clip.sha(Data(s.utf8))
            record(fp) {
                var item = ClipItem(kind: Clip.classify(s), text: s, fingerprint: fp)
                item.rtf = small(pb.data(forType: .rtf))
                item.html = small(pb.data(forType: .html))
                item.chars = s.count
                item.lines = s.reduce(into: 1) { if $1 == "\n" { $0 += 1 } }
                return item
            }
            return
        }

        guard Prefs.shared.saveImages, let png = pngData(), png.count < Self.imageLimit else { return }
        let fp = "image:" + Clip.sha(png)
        record(fp) {
            let name = UUID().uuidString + ".png"
            do {
                try png.write(to: store.imagesDir.appendingPathComponent(name))
            } catch {
                NSLog("WolfClip: failed to store image: \(error)")
                return nil
            }
            let rep = NSBitmapImageRep(data: png)
            var item = ClipItem(kind: .image, fingerprint: fp)
            item.imageFile = name
            item.pixelWidth = rep?.pixelsWide
            item.pixelHeight = rep?.pixelsHigh
            return item
        }
    }

    private func small(_ data: Data?) -> Data? {
        guard let data, data.count <= Self.richLimit else { return nil }
        return data
    }

    private func pngData() -> Data? {
        if let png = pb.data(forType: .png) { return png }
        if let tiff = pb.data(forType: .tiff), let rep = NSBitmapImageRep(data: tiff) {
            return rep.representation(using: .png, properties: [:])
        }
        return nil
    }
}
